include: [compose.yaml]
#####################
# WEI Core Services #
#####################
services:
  wei_server:
    image: ghcr.io/ad-sdl/wei
    container_name: wei_server
    ports:
      - 8000:8000
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1 # Fix weird bug with empty logging
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - ./tests/workcell_defs:/workcell_defs
      - ${WEI_DATA_DIR}:/home/app/.wei
      - diaspora_config:/home/app/.diaspora
    command: python3 -m wei.server --workcell /workcell_defs/${WORKCELL_FILENAME} --autostart_engine True
    depends_on:
      - wei_redis
  wei_redis:
    image: redis
    container_name: wei_redis
    ports:
      - 6379:6379
    volumes:
      - ${REDIS_DIR}:/data
    command: redis-server --save 60 1 --loglevel warning

####################
# PostgreSQL Setup #
####################
  # wei_postgres:
  #   image: postgres:13
  #   container_name: wei_postgres
  #   environment:
  #     POSTGRES_USER: rpl
  #     POSTGRES_PASSWORD: rpl
  #     POSTGRES_DB: resources
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

################
# Data Storage #
################
volumes:
  diaspora_config:
    driver: local
  pgdata:
    driver: local
