rpl_ur_move:
  ros__parameters:

    controller_name: "joint_trajectory_controller"

    goal_names: ["pos1", "pos2"]
    pos1: [-1.57, -1.35, -2.61, -0.75, 1.57, 0.0]
    pos2: [-1.57, -1.35, -2.61, -0.75, 1.57, 0.0]

    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: false
    starting_point_limits:
      shoulder_pan_joint: [-1.6,-1.5]
      shoulder_lift_joint: [-0.1,0.1]
      elbow_joint: [-2.3,-2.2]
      wrist_1_joint: [-0.9,-0.8]
      wrist_2_joint: [1.5,1.6]
      wrist_3_joint: [-0.1,0.1]

    gripper_close_pos: 38