Import('env')

HW_SOURCE = Split('''server.cpp
                     utilities.cpp
                     XMLRPCConverters.cpp
                     ''')

HW_CPPPATH = Split('''.
                      ''')

HW_LIBPATH = Split('''.
                      ''')

HW_LIBS = Split('''
                   m
                   rt
                   pthread
                   ''')

HW_CPPPATH.append(env['CPPPATH'])
HW_LIBPATH.append(env['LIBPATH'])
HW_LIBS.append(env['LIBS'])


###############################################################################

env.Program(target = 'server',
            source = HW_SOURCE,
            CPPPATH = HW_CPPPATH,
            LIBPATH = HW_LIBPATH,
            LIBS = HW_LIBS)

