name: Pytest Unit Tests

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
      - name: Test makefile
        run: make init .env
      - name: Check .env file
        run: cat .env
      - name: Create paths
        run: make paths
      - name: Initialize, Build, and Test with Docker
        run: make test
        shell: bash
